### ISSUE TITLE
strange behavior with certain libraries d3/angular.js

### ISSUE THREAD

**Issue by gad2103** [fmal/gulp-inline-source#11]
when i try to inline minified js for these libraries, a bunch of stuff gets put in the body tag. i'm guessing that something is triggering functions to run inside these libraries during the inlining? here's a picture of d3:
![screen shot 2015-01-30 at 12 56 20 pm](https://cloud.githubusercontent.com/assets/1045265/5980546/7b5b94c2-a87f-11e4-961a-d98e08f575eb.png)

any ideas?

**Comment by fmal** [comment]
You're inlining already minified assets. Disabling compression should probably solve your issue:

```
inlinesource({ compress: false })
```
