### ISSUE TITLE
update inline-source version to 1.2.X

### ISSUE THREAD

**Issue by hanifbbz** [fmal/gulp-inline-source#12]
Hi,

The latest version of inline-source has introduced a couple of options that we need so badly. Do you mind updating the package.json file to use the latest version of that library?

Thanks

**Comment by fmal** [comment]
Hi. Sure - I'll do the update later today.

**Comment by hanifbbz** [comment]
we used shrinkwrap to forcefully use 1.2.0 and it works just fine so I guess it's just a matter of updating the package.json.

**Comment by oskar** [comment]
The package is not updated yet, can you please fix this? Thanks.

Maybe you can also consider changing: `"inline-source": "~1.0.0"` to `"inline-source": "~1"`

**Comment by fmal** [comment]
Done. Sorry for the delay!
