### ISSUE TITLE
inline source version bump.

### ISSUE THREAD

**Issue by sticilface** [fmal/gulp-inline-source#30]
I've had some issues with inline-source and may have found a bug that has now been fixed. 
https://github.com/popeindustries/inline-source/issues/45#issuecomment-247141003

How can I / is it possible to pull version 5.0.2 into gulp-inline-source? 

cheers

**Comment by fmal** [comment]
Hi,

this plugin is configured to use the most recent minor version of `inline-source` so it should pull 5.0.2 when you reinstall package.
