### ISSUE TITLE
Feature request: Can you add an option for CSP SHA hashes to be generated automatically?

### ISSUE THREAD

**Issue by riklewis** [fmal/gulp-inline-source#35]
It would be really handy when inlining javascript and styles for the CSP SHA256 hash to be generated and added as an attribute automatically. 

For more information, look here... [https://scotthelme.co.uk/csp-cheat-sheet/#hashes](https://scotthelme.co.uk/csp-cheat-sheet/#hashes)

**Comment by fmal** [comment]
@riklewis I believe you can utliize https://github.com/popeindustries/inline-source#custom-handlers for that. Use something like https://nodejs.org/api/crypto.html to compute checksum and then set your custom `source.replace` with the attribute in the handler.
