### ISSUE TITLE
ES6+ causes script inline to fail silently

### ISSUE THREAD

**Issue by sstadt** [fmal/gulp-inline-source#37]
I was having issues getting a script in my project to inline through this plugin and was able to track it down to ES6 code causing the entire file to be skipped by gulp during this task.

The following is a contrived example that will reproduce the issue.

```js
// gulpfile.js
var gulp = require('gulp');
var inlinesource = require('gulp-inline-source');

gulp.task('default', function () {
    return gulp.src('index.html')
        .pipe(inlinesource())
        .pipe(gulp.dest('./out'));
});
```

```html
<!-- index.html -->
<html>
  <head>
    <script src="script.js" inline></script>
  </head>
  <body>
  </body>
</html>
```

```js
// scripts.js (working)
function p(msg) {
  var today = new Date();
  console.log('[' + today.getHours() + ':' + today.getMinutes() + ':' + today.getSeconds() + '] ' + msg);
}
```

```html
<!-- output - script.js is parsed -->
<html>
  <head>
    <script>function p(e){var n=new Date;console.log("["+n.getHours()+":"+n.getMinutes()+":"+n.getSeconds()+"] "+e)}</script>
  </head>
  <body>
  </body>
</html>
```

```js
// script.js (not working)
function p(msg) {
  var today = new Date();
  console.log(`[${today.getHours()}:${today.getMinutes()}:${today.getSeconds()}] ${msg}`);
}
```

```html
// output - script.js is completely skipped
<html>
  <head>
    <script src="script.js" inline></script>
  </head>
  <body>
  </body>
</html>
```

I'm sure babel transpiling is not something that should be built into the default module, but there should be some kind of warning that a flagged tag is being skipped, and why. Currently, the asset is skipped silently.

**Comment by sstadt** [comment]
Here is a custom handler for anyone else running into this issue:

```
let babelOptions = { presets: ['es2015', 'stage-0'], minified: true };

function (source, context, next) {
  if (source.fileContent && !source.content && (source.type == 'js')) {
      source.content = babelCore.transform(source.fileContent, babelOptions).code;
      next();
  } else {
    next();
  }
}
```

**Comment by fmal** [comment]
@sstadt good catch, see https://github.com/popeindustries/inline-source/pull/60. When it's merged the `inline-source` will throw when trying to compress non-ES5 syntax (which uglify-js can't handle) and the plugin will propagate the error. Alternatively you could disable compression and use some ES6+ aware minifier inside a custom handler.
